# Generated by Django 3.0.8 on 2020-08-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('family', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.BigIntegerField()),
            ],
        ),
    ]
